---
- hosts: all
  sudo: yes
  tasks:

    - name: enable https apt functionality
      apt: name=apt-transport-https update_cache=yes

    - name: add nodesource key to apt
      apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key

    - name: add nodesource repo to apt
      apt_repository: repo="{{ item }}"
      with_items:
        - deb https://deb.nodesource.com/node {{ ansible_lsb.codename }} main
        - deb-src https://deb.nodesource.com/node {{ ansible_lsb.codename }} main

    - name: install packages from apt
      apt: name={{ item }} 
      with_items:
        - libjpeg-dev
        - postgresql
        - python2.7-dev
        - python-pip
        - python-psycopg2
        - nodejs
        - git

    - name: install modules from node
      npm: name={{ item }} global=yes
      with_items:
        - yuglify
        - less

- hosts: all
  sudo: yes
  sudo_user: postgres
  tasks:
    - name: create database chalktalk_dev
      postgresql_db: name=chalktalk_dev

    - name: create postgres user vagrant with access to chalktalk_dev
      postgresql_user: db=chalktalk_dev name=vagrant

- hosts: all
  remote_user: vagrant
  tasks:
    - name: clone git repo into shared folder
      git: repo={{ vagrant_git_repo }} dest=/vagrant/src
      
