---
- hosts: all
  sudo: yes
  tasks:

    - name: enable https apt functionality
      apt: name=apt-transport-https update_cache=yes

    - name: add nodesource key to apt
      apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key

    - name: add nodesource repo to apt
      apt_repository: repo="{{ item }}"
      with_items:
        - deb https://deb.nodesource.com/node {{ ansible_lsb.codename }} main
        - deb-src https://deb.nodesource.com/node {{ ansible_lsb.codename }} main

    - name: install packages from apt
      apt: name={{ item }} 
      with_items:
        - libjpeg-dev
        - libfontconfig
        - postgresql-9.1
        - postgresql-server-dev-9.1
        - python2.7-dev
        - python-psycopg2
        - python-pip
        - nodejs
        - git

- hosts: all
  sudo: yes
  sudo_user: postgres
  tasks:
    - name: create database vagrant
      postgresql_db: name=vagrant

    - name: create postgres user vagrant with access to vagrant
      postgresql_user: db=vagrant name=vagrant role_attr_flags=CREATEDB
